source 'https://rubygems.org'

gem 'rails',      '3.2.12'
gem 'rails-api',  '0.0.3'

gem 'ffi-rzmq'
gem 'yajl-ruby'

group :assets do
  gem 'coffee-rails',    '3.2.2'
  gem 'uglifier',        '1.3.0'
  gem 'angularjs-rails', '1.0.5'
  gem 'haml',            '4.0.0'
  gem 'sass-rails',      '3.2.6'
  gem 'compass-rails',   '1.0.3'
  gem 'bootstrap-sass',  '2.3.0.1'
end

group :development do
  gem 'coffee-rails-source-maps'
  gem 'pry-nav'
  gem 'binding_of_caller'
  gem 'better_errors'
end
