source 'https://rubygems.org'

gem 'rails',      '3.2.11'
gem 'rails-api',  '0.0.3'

gem 'ffi-rzmq'

group :assets do
  gem 'coffee-rails',    '3.2.2'
  gem 'uglifier',        '1.3.0'
  gem 'angularjs-rails', '1.0.3'
  gem 'haml',            '3.2.0.rc.4'
  gem 'sass-rails',      '3.2.6'
  gem 'compass-rails',   '1.0.3'
  gem 'bootstrap-sass',  '2.2.2.0'
end

group :development do
  gem 'pry-nav'
  gem 'binding_of_caller'
  gem 'better_errors'
end
